"""Compile canonical design tokens. --check detects stale generated outputs."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DS = ROOT / "brand/design-system"
PACKAGE = ROOT / "src/energy_analytics/visualization"
SOURCE = DS / "tokens/design-tokens.json"


def resolve_tokens(tokens):
    resolved = {}

    def resolve(name, stack=()):
        if name in stack:
            raise ValueError(f"Cyclic token reference: {' -> '.join((*stack, name))}")
        if name not in tokens:
            raise ValueError(f"Unknown token: {name}")
        if name not in resolved:
            resolved[name] = re.sub(
                r"var\(--([\w-]+)\)",
                lambda match: resolve(match[1], (*stack, name)),
                tokens[name],
            )
        return resolved[name]

    for name in tokens:
        resolve(name)
    return resolved


def compile_outputs(source=SOURCE):
    config = json.loads(source.read_text(encoding="utf-8"))
    if config.get("version") != 1:
        raise ValueError("Unsupported token format")
    raw = config["tokens"]
    t = resolve_tokens(raw)
    chart = config["chart"]
    roles = {k: t[v] for k, v in chart["roles"].items()}
    customers = {k: t[v] for k, v in chart["customers"].items()}
    palette = [t[k] for k in chart["palette"]]
    seq = [t[k] for k in chart["sequential"]]
    div = [t[k] for k in chart["diverging"]]

    def number(key):
        return float(t[key].removesuffix("px"))

    font = t["font-chart"]
    axis = dict(
        showgrid=False,
        zeroline=False,
        showline=True,
        linecolor=t["data-grid"],
        ticks="outside",
        ticklen=4,
        tickcolor=t["data-grid"],
        automargin=True,
        tickangle=0,
        nticks=6,
        tickfont=dict(family=font, size=12, color=t["text-muted"]),
        title=dict(font=dict(family=font, size=12, color=t["text-muted"]), standoff=12),
    )
    layout = dict(
        font=dict(family=font, size=number("chart-font-size"), color=t["text-primary"]),
        title=dict(
            font=dict(family=font, size=number("chart-title-size")),
            x=0,
            xanchor="left",
            y=0.96,
            pad=dict(b=12),
        ),
        paper_bgcolor=t["chart-paper-bg"],
        plot_bgcolor=t["chart-plot-bg"],
        colorway=palette,
        separators=",.",
        colorscale=dict(
            sequential=[[i / (len(seq) - 1), c] for i, c in enumerate(seq)],
            diverging=[[i / (len(div) - 1), c] for i, c in enumerate(div)],
        ),
        xaxis=axis,
        yaxis={
            **axis,
            "showgrid": True,
            "gridcolor": t["data-grid"],
            "gridwidth": 1,
            "showline": False,
            "separatethousands": True,
            "tickformat": ",~g",
        },
        legend=dict(
            orientation="h",
            yanchor="bottom",
            y=1.02,
            xanchor="left",
            x=0,
            font=dict(family=font, size=12, color=t["text-muted"]),
            bgcolor="rgba(0,0,0,0)",
            title=dict(text=""),
        ),
        margin=dict(l=64, r=24, t=64, b=48),
        hoverlabel=dict(
            bgcolor=t["surface-card"],
            bordercolor=t["border-default"],
            font=dict(family=font, size=12, color=t["text-primary"]),
            align="left",
        ),
        hovermode="x unified",
        bargap=number("chart-bar-gap"),
        barcornerradius=number("chart-bar-radius"),
    )
    data = dict(
        tokens=t,
        roles=roles,
        customers=customers,
        palette=palette,
        sequential=seq,
        diverging=div,
        plotly={"layout": layout},
    )

    def dumps(obj):
        return json.dumps(obj, indent=2, ensure_ascii=False) + "\n"

    css = "/* Generated by scripts/build_tokens.py. Edit tokens/design-tokens.json. */\n:root {\n"
    css += "".join(f"  --{key}: {value};\n" for key, value in raw.items()) + "}\n"
    mpl = {
        "figure.facecolor": t["chart-paper-bg"],
        "figure.dpi": "120",
        "savefig.dpi": "200",
        "savefig.facecolor": t["chart-paper-bg"],
        "savefig.bbox": "tight",
        "font.family": "sans-serif",
        "font.sans-serif": "IBM Plex Sans, Segoe UI, DejaVu Sans",
        "font.size": "12",
        "text.color": t["text-primary"],
        "axes.facecolor": t["chart-plot-bg"],
        "axes.edgecolor": t["data-grid"],
        "axes.labelcolor": t["text-muted"],
        "axes.labelsize": "12",
        "axes.titlesize": "15",
        "axes.titleweight": "600",
        "axes.titlelocation": "left",
        "axes.titlecolor": t["text-primary"],
        "axes.titlepad": "14",
        "axes.spines.top": "False",
        "axes.spines.right": "False",
        "axes.spines.left": "False",
        "axes.grid": "True",
        "axes.grid.axis": "y",
        "axes.formatter.use_locale": "False",
        "axes.prop_cycle": "cycler('color', " + repr([c.lstrip("#") for c in palette]) + ")",
        "grid.color": t["data-grid"],
        "grid.linewidth": "1",
        "grid.alpha": "1",
        "xtick.color": t["text-muted"],
        "ytick.color": t["text-muted"],
        "xtick.labelsize": "12",
        "ytick.labelsize": "12",
        "xtick.direction": "out",
        "ytick.direction": "out",
        "lines.linewidth": t["chart-line-width"].removesuffix("px"),
        "lines.markersize": t["chart-marker-size"].removesuffix("px"),
        "lines.solid_capstyle": "round",
        "legend.frameon": "False",
        "legend.fontsize": "12",
        "legend.labelcolor": t["text-muted"],
    }
    mpl_text = "# Generated by scripts/build_tokens.py.\n" + "".join(
        f"{key}: {value.lstrip('#')}\n" for key, value in mpl.items()
    )
    return {
        DS / "dist/css/tokens.css": css,
        DS / "dist/js/tokens.js": "// Generated by scripts/build_tokens.py.\nwindow.SWWTokens = "
        + dumps(data).rstrip()
        + ";\n",
        DS / "dist/tokens.resolved.json": dumps(data),
        DS / "dist/plotly/template.json": dumps(data["plotly"]),
        DS / "dist/matplotlib/sww.mplstyle": mpl_text,
        PACKAGE / "_tokens.json": dumps(data),
        PACKAGE / "sww.mplstyle": mpl_text,
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for path, content in compile_outputs().items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != content:
                stale.append(str(path.relative_to(ROOT)))
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8", newline="\n")
    if stale:
        raise SystemExit("Run python scripts/build_tokens.py; stale files:\n" + "\n".join(stale))
    print("Design tokens checked." if args.check else "Design tokens generated.")


if __name__ == "__main__":
    main()
